name: ci

on:
  push:

jobs:
  testo:
    runs-on: ubuntu-latest
    steps:
      - name: Install DEPS
        run: |
          sudo apt update
          sudo apt install libvirt0 libvirt-clients libvirt-daemon-system libguestfs0 qemu qemu-kvm ebtables dnsmasq-base
      - name: Install testo framework
        run: |
          wget https://github.com/log0div0/testo/releases/download/v3.6.8/testo-3.6.8.deb
          wget https://github.com/log0div0/testo/releases/download/v3.6.8/testo-nn-server-3.6.8.deb
          sudo dpkg -i testo-3.6.8.deb testo-nn-server-3.6.8.deb
          sudo testo version
      - name: Install Ubuntu ISO
        run: |
          sudo mkdir -p /opt/iso
          wget -O /opt/iso/ubuntu_server.iso https://releases.ubuntu.com/16.04/ubuntu-16.04.7-server-amd64.iso
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests
        run: |
          mkdir -p ./output/testo
          sudo testo run ./ubuntu_installation.testo --report_format=native_local --report_folder=output/testo
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: testo-results
          path: output/testo/
          overwrite: true
          
  
